### ISSUE TITLE
t/URT/t/04e_file_track_open_close.t failures

### ISSUE THREAD

**Issue by ntyni** [genome/UR#126]
We're seeing sporadic failures of t/URT/t/04e_file_track_open_close.t test 8, easily reproducible by running the test in a loop.

> t/URT/t/04e_file_track_open_close.t .. 
1..100
ok 1 - Got an object from the file
ok 2 - it has the correct name
ok 3 - new() was called on the file handle
ok 4 - open() was called on the file handle
ok 5 - close() was not called on the file handle
ok 6 - seek() was called on the file handle
ok 7 - seek() was to the correct position
not ok 8 - Got second object from the file
\#   Failed test 'Got second object from the file'
\#   at t/URT/t/04e_file_track_open_close.t line 89.
Can't call method "name" on an undefined value at t/URT/t/04e_file_track_open_close.t line 90, <GEN3> line 3.
\# Looks like you planned 100 tests but ran 8.
\# Looks like you failed 1 test of 8 run.
\# Looks like your test exited with 255 just after 8.
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 93/100 subtests 

Instrumenting with UR_DBI_MONITOR_SQL=1, I see that normally after test 7 we get

>  ok 7 - seek() was to the correct position
FILE: /tmp/y0ex87OzdE
FILTERS letter_id = 2 (sorted)
FILE: FIRST FETCH TIME: 0.0010 s
FILE: Resetting file position to 0
FILE: First match after reading 2 lines
FILE: 3 lines read for this request.  1 matches
FILE: TOTAL EXECUTE-FETCH TIME: 0.0012 s
ok 8 - Got second object from the file

but when it fails we get

> ok 7 - seek() was to the correct position
FILE: /tmp/UlXM_EoEEv
FILTERS letter_id = 2 (sorted)
FILE: FIRST FETCH TIME: 0.0010 s
FILE: 1 lines read for this request.  0 matches
FILE: TOTAL EXECUTE-FETCH TIME: 0.0011 s
not ok 8 - Got second object from the file

It looks like the [read fingerprint](https://github.com/genome/UR/blob/b63a182d2250faeafb22726cba2ff978c52b8148/lib/UR/DataSource/File.pm#L851) in UR::DataSource::File is equal between the two calls when it fails. Maybe the memory position for the CODE block gets reused, inadvertently giving the same stringification twice?

Many thanks for your work.

**Comment by brummett** [comment]
You were right, the ref address was getting re-used.  I've merged in a fix via #127, and it'll be part of the next release.

Thanks!
