### ISSUE TITLE
Limit has unexpected behavior when there are less returned objects than the specified limit

### ISSUE THREAD

**Issue by acoffman** [genome/UR#79]
So, I ran into this issue today and it surprises me that it hasn't cropped up before, so maybe I'm doing something wrong or this is expected?

When using a `-limit` in a query, if there are less objects than match the query parameters, the remainder of the `limit` value is padded with `undef`. In other words, `SomeObject->get(this_will_only_get_me_one_object => 'true', -limit => 3);` will return `($obj, undef, undef)`

Below is a complete example that reproduces the effect.

````perl
use UR;

use strict;
use warnings;

package Blah;
class Blah {
    is => 'UR::Object',
    has => {
        name => { is => 'Text' },
    },
};

Blah->create(name => "Hi");
Blah->create(name => "Hello");

my @items = Blah->get(name => 'Hi', -limit => 20);

print scalar(@items) . "\n";  #prints 20

1;
````

**Comment by tmooney** [comment]
Looks like the trouble is [here](https://github.com/genome/UR/blob/2ef9718e48871670e7e61a8fcf9481f91c4ec10f/lib/UR/Context.pm#L1872).  We're potentially increasing the size of the list there.  In the case where we also query the DB this doesn't come up, but for a cache-only query it returns the result of the prune call directly.
